### ISSUE TITLE
Old supertype syntax used

### ISSUE THREAD

**Issue by kdambekalns** [Flowpack/Flowpack.SimpleSearch.ContentRepositoryAdaptor#17]
It should be

    'Flowpack.SimpleSearch.ContentRepositoryAdaptor:Search':
      superTypes:
        'TYPO3.Neos:Content': true

**Comment by kdambekalns** [comment]
@kitsunet Could you help me out with the expected compatibilities between branches here and Neos versions? Then I'd create a PR.

**Comment by kitsunet** [comment]
So far all releases and branches should basically be compatible with anything starting from Neos 1.2, so this change should probably go to master and then I would prepare to make master a 2.0 release.
