### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by mfMeds** [Flowpack/Flowpack.SimpleSearch.ContentRepositoryAdaptor#29]
## Neos 4.0

Hey, i have a problem with your package, i proceeded as follows:

1) composer require flowpack/simplesearch-contentrepositoryadaptor:2.0.2
2) composer update

> 
> Problem 1
>     - Conclusion: remove neos/neos 4.0.8
>     - Conclusion: don't install neos/neos 4.0.8
>     - Conclusion: don't install neos/neos 4.0.7
>     - Conclusion: don't install neos/neos 4.0.6
>     - Conclusion: don't install neos/neos 4.0.5
>     - Conclusion: don't install neos/neos 4.0.4
>     - Conclusion: don't install neos/neos 4.0.3
>     - Conclusion: don't install neos/neos 4.0.2
>     - Conclusion: don't install neos/neos 4.0.0
>     - flowpack/simplesearch-contentrepositoryadaptor 2.0.2 requires neos/neos ~3.0 || dev-master -> satisfiable by neos/neos[3.0.x-dev, 3.1.x-dev, 3.2.x-dev, 3.3.x-dev, dev-master].
>     - flowpack/simplesearch-contentrepositoryadaptor 2.0.x-dev requires neos/neos ~3.0 || dev-master -> satisfiable by neos/neos[3.0.x-dev, 3.1.x-dev, 3.2.x-dev, 3.3.x-dev, dev-master].
>     - Can only install one of: neos/neos[4.0.x-dev, 3.0.x-dev].
>     - Can only install one of: neos/neos[4.0.x-dev, 3.1.x-dev].
>     - Can only install one of: neos/neos[4.0.x-dev, 3.2.x-dev].
>     - Can only install one of: neos/neos[4.0.x-dev, 3.3.x-dev].
>     - Can only install one of: neos/neos[dev-master, 4.0.x-dev].
>     - Installation request for neos/neos ~4.0.0 -> satisfiable by neos/neos[4.0.0, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.x-dev].
>     - Installation request for flowpack/simplesearch-contentrepositoryadaptor ~2.0.2 -> satisfiable by flowpack/simplesearch-contentrepositoryadaptor[2.0.2, 2.0.x-dev].

Here is my composer.json
https://gist.github.com/mfMeds/5e13cc40ee2799b956445bc5acdcf391

Best Regards!

**Comment by drlimbo** [comment]
same here

**Comment by mfMeds** [comment]
Any Fix?

**Comment by zabusm** [comment]
I have the same problem

**Comment by mfMeds** [comment]
Thanks 
> composer require flowpack/simplesearch-contentrepositoryadaptor:2.0.3

Works!
