### ISSUE TITLE
Hide Nodes from Results / add notEquals() Filter

### ISSUE THREAD

**Issue by paavo** [Flowpack/Flowpack.SimpleSearch.ContentRepositoryAdaptor#30]
Im looking for a way to **hide nodes with metaRobotsNoindex TRUE** from search results. 
A **notEquals()** Filter (like in ElasticSearch.ContentRepositoryAdaptor) would be great!
`${Search.query(site).nodeType('Neos.Neos:Document').notEquals('metaRobotsNoindex', TRUE)`

**Comment by drlimbo** [comment]
@kitsunet any plans to "fix" this problem?
it's ugly when "Hidden-Pages" (Hidden in Menu) for example the 404-Page appear in search results..

thanks!

**Comment by Benjamin-K** [comment]
What about `Search.query(site).nodeType('Neos.Neos:Document').exactMatch('metaRobotsNoindex', false)...`?
