### ISSUE TITLE
Support Neos 5

### ISSUE THREAD

**Issue by putzwasser** [Flowpack/Flowpack.SimpleSearch.ContentRepositoryAdaptor#32]
If you try to install this package in a Neos 5 enviroment a fairly old version gets installed. Therefore it's unusable because the package tries to use the very old `TYPO3\Flow`, etc classes.

**Comment by henrik-d** [comment]
Is this package still maintained? I also can't migrate to Neos 5.
` flowpack/simplesearch-contentrepositoryadaptor 2.0.3 requires neos/neos ~3.0 || ~4.0 || dev-master -> satisfiable by neos/neos[4.3.5, 3.0.0, 3.0.1, 3.0.10, 3.0.11, 3.0.12, 3.0.13, 3.0.14, 3.0.15, 3.0.16, 3.0.17, 3.0.18, 3.0.19, 3.0.2, 3.0.20, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.1.0, 3.1.1, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.2.0, 3.2.1, 3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.3.0, 3.3.1, 3.3.10, 3.3.11, 3.3.12, 3.3.13, 3.3.14, 3.3.15, 3.3.16, 3.3.17, 3.3.18, 3.3.19, 3.3.2, 3.3.20, 3.3.21, 3.3.22, 3.3.23, 3.3.24, 3.3.25, 3.3.26, 3.3.27, 3.3.28, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9, 4.0.0, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.1.0, 4.1.1, 4.1.10, 4.1.11, 4.1.12, 4.1.13, 4.1.14, 4.1.15, 4.1.16, 4.1.17, 4.1.18, 4.1.19, 4.1.2, 4.1.20, 4.1.21, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.1.9, 4.2.0, 4.2.1, 4.2.10, 4.2.11, 4.2.12, 4.2.13, 4.2.14, 4.2.15, 4.2.16, 4.2.17, 4.2.2, 4.2.3, 4.2.4, 4.2.5, 4.2.6, 4.2.8, 4.2.9, 4.3.0, 4.3.1, 4.3.10, 4.3.2, 4.3.3, 4.3.4, 4.3.6, 4.3.7, 4.3.8, 4.3.9].`

Is this just a cdeclaration issue or are code changes required to make this package work with Neos 5?

**Comment by kitsunet** [comment]
Done with release 3.0
