### ISSUE TITLE
Neos 7.x compatibility

### ISSUE THREAD

**Issue by Benjamin-K** [Flowpack/Flowpack.SimpleSearch.ContentRepositoryAdaptor#38]
Currently, this package is not compatible with Neos 7.0+. Please update this package so we can upgrade our websites to Neos 7.0.

**Comment by putzwasser** [comment]
I'd be thankful, too

**Comment by mberhorst** [comment]
+1

**Comment by Benjamin-K** [comment]
Fixed with #39 already, so i'll close.
